services:
  postgres:
    image: postgres:16-alpine
    container_name: stream-postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: stream_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: stream-adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
